[[plugins]] # sayonara!
repo = 'mhinz/vim-sayonara'
on_cmd = 'Sayonara'
hook_add = '''
  command! -bar -nargs=* -complete=file -range=% -bang WQ
    \ <line1>,<line2>write<bang> <args> | :Sayonara
  command! -bar Q :Sayonara
  cabbrev q <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'Q' : 'q')<CR>
  cabbrev wq <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'WQ' : 'wq')<CR>
'''

[[plugins]] # haskell
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]] # Idris
repo = 'idris-hackers/idris-vim'
on_ft = 'idris'

[[plugins]] # Elm
repo = 'elmcast/elm-vim'
on_ft = 'elm'

[[plugins]] # F sharp
repo = 'kongo2002/fsharp-vim'
on_ft = 'fsharp'

[[plugins]] # elixir
repo = 'elixir-editors/vim-elixir'
on_ft = 'elixir'

[[plugins]] # import 文のソート
repo = 'itchyny/vim-haskell-sort-import'
on_ft = 'haskell'

[[plugins]] # scala
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]] # kotlin
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

[[plugins]] # go
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # solidity
repo = 'tomlion/vim-solidity'
on_ft = 'solidity'

[[plugins]] # better javascript
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]] # jsx
repo = 'chemzqm/vim-jsx-improve'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]] # dart
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]] # coffeescript
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]] # typescript
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]] # purescript
repo = 'raichoo/purescript-vim'
on_ft = 'purescript'

[[plugins]] # fishscript
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]] # GraphQL
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

[[plugins]] # nginx
repo = 'chr4/nginx.vim'
on_ft = 'nginx'

[[plugins]] # TOML
repo = 'cespare/vim-toml'
on_ft = 'toml'
